### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Aifrion/Dasmotos#6]
https://github.com/Aifrion/Dasmotos/blob/master/css/styles.css#L1-L20

Nice job using more general selectors like `html` and `h2` so that you can consolidate shared styles in one location and keep your CSS tidy and maintainable. 👍 

If you'd used `div` tags with the same class, you could write the following selector which is a little more specific than `h2` in case you later introduce `h2` tags that should be styled differently from the ones in the product sections.

```css
.product h2 {
  font-size: 32px;
  color: white;
}
```
